default_platform(:ios)

platform :ios do
  desc "Build the iOS app without code signing"
  lane :build do
    build_app(
      scheme: "IosGithubActionBuild",              # Replace with your actual scheme
      workspace: "IosGithubActionBuild.xcworkspace", # Replace with the actual workspace name
      configuration: "Debug",                      # Or "Release" if needed
      export_method: "ad-hoc",                     # Try "ad-hoc" for builds without App Store distribution
      skip_package_ipa: true,                      # Skip the IPA packaging step
      xcargs: "CODE_SIGNING_ALLOWED=NO"            # Disable code signing
    )
  end
end
