# .github/workflows/ios-build.yml
name: Android Build and Deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest # Uses macOS runner with Xcode pre-installed

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK Tools
        # uses: android-actions/setup-android@00854ea68c109d98c75d956347303bf7c45b0277
        uses: android-actions/setup-android@v3.2.1

      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js 22
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install Fastlane
        run: gem install fastlane -NV
      - name: Install npm dependencies
        run: npm install

      - name: Build Android App
        run: cd android && ./gradlew bundleRelease && ls app/build/outputs/bundle/release
