# .github/workflows/ios-build.yml
name: iOS Build and Deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest # Uses macOS runner with Xcode pre-installed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js 22
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install Fastlane
      - name: Install Fastlane
        run: |
          brew install fastlane
      # Install dependencies
      - name: Install npm dependencies
        run: npm install

      - name: Install pod dependencies
        run: cd ios && pod install
      # Build the iOS app
      - name: Build iOS App
        run: cd android && bundle exec fastlane beta
